export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_USERS = "SET_USERS"
export const SET_IS_FETCHING = "SET_IS_FETCHING"
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_ALL_USERS = "SET_ALL_USERS"

export const SET_FORMS = "SET_FORMS"
export const SET_GROUPS = "SET_GROUPS"
export const SET_COUNTRIES = "SET_COUNTRIES"
export const SET_TYPES = "SET_TYPES"
export const SET_NAMES = "SET_NAMES"
export const SET_AREAS = "SET_AREAS"
export const SET_REASONS = "SET_REASONS"
export const SET_CURRENT_AREA = "SET_CURRENT_AREA"
export const UPDATE_INPUT = "UPDATE_INPUT"
export const SET_CURRENT_COUNTRY = "SET_CURRENT_COUNTRY"
export const UPDATE_INPUT_COUNTRY = "UPDATE_INPUT_COUNTRY"
export const SET_CURRENT_FORM = "SET_CURRENT_FORM"
export const UPDATE_INPUT_FORM = "UPDATE_INPUT_FORM"
export const SET_CURRENT_PHARMACOLOGICAL_GROUP = "SET_CURRENT_PHARMACOLOGICAL_GROUP"
export const UPDATE_INPUT_PHARMACOLOGICAL_GROUP = "UPDATE_INPUT_PHARMACOLOGICAL_GROUP"
export const SET_CURRENT_PHARMACY_NAME = "SET_CURRENT_PHARMACY_NAME"
export const UPDATE_INPUT_PHARMACY_NAME = "UPDATE_INPUT_PHARMACY_NAME"